### ISSUE TITLE
No puedo iniciar el servidor

### ISSUE THREAD

**Issue by Gsushimabuko** [ulima-pw/help_20212#24]
Estoy teniendo este error al poner node index.js:

Error: listen EADDRINUSE: address already in
use :::4444
    at Server.setupListenHandle [as _listen2] (net.js:1331:16)
    at listenInCluster (net.js:1379:12)
    at Server.listen (net.js:1465:7)
    at Function.listen (C:\Users\Microsoft\Desktop\backend\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (C:\Users\Microsoft\Desktop\backend\index2.js:58:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1358:8)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 4444
}
PS C:\Users\Microsoft\Desktop\backend>

**Comment by billygl** [comment]
# problema
- se está teniendo conflicto en el mismo puerto

# solución
- verificar que no haya otra app corriendo en otra ventana
- cambiar de puerto
